### ISSUE TITLE
Improve the layout of the CardView

### ISSUE THREAD

**Issue by abhi211199** [AASF-IIITM/AndroidDB#2]
The current UI of the cards looks pathetic! 
<img src="https://user-images.githubusercontent.com/36303692/94478305-baa3ae00-01f0-11eb-8a18-ed3886447298.png" height="500px"></img>
Please upgrade the UI by using libraries like [material.io](https://material.io/develop/android/components/cards).

**Comment by debangeedas** [comment]
Hey! I would like to give it a shot! Mind assigning it to me?

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by Adityashukla2000** [comment]
Hey! I would like to give it a shot! Mind assigning it to me?

**Comment by priyansh-jain10** [comment]
Hey! I would like to give it a shot! Mind assigning it to me?

**Comment by manikmmalhotra** [comment]
I would like to work on this issue

**Comment by abhi211199** [comment]
@manikmmalhotra assigned to you!
